spring:
  h2:
    console:
      enabled: true
      path: /h2

spring:
  datasource:
    url: jdbc:h2:file:/home/thiago/dbh2history
    username: sa
    password:
    driver-class-name: org.h2.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
